### ISSUE TITLE
FIBONACCI SERIES

### ISSUE THREAD

**Issue by BTANISHA11** [DhananjayPorwal/hacktoberfest2022#316]
### Add Fibonacci series in C
I want to add program for fibonacci series in C @DhananjayPorwal

**Comment by SRR-CODER** [comment]
Interested in this plz assign it to me @BTANISHA11 will complete within 15 mins.

**Comment by aritroo** [comment]
Hello @DhananjayPorwal  I want to work on it and I will ad a fibonacci series code in python . Please assign me

**Comment by BTANISHA11** [comment]
> ### Add Fibonacci series in C
> I want to add program for fibonacci series in C @DhananjayPorwal 

Pls assign this to me
